version: '3'
services:
  maria:
    image: mariadb:10.7.8-focal
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=oauthserver
      - MARIADB_USER=oauthserver
      - MARIADB_PASSWORD=oauthserver
    volumes:
       - identity_data:/var/lib/mysql  
volumes:
  identity_data:
    driver: local